@startuml
title CIED Connectivity Data Model

hide circle

skinparam linetype ortho

entity "Patient" as Patient {
  id : string <<generated>>
  --
  identifier : Identifier: (0..*)
  name : HumanName (0..*)
  telecom: ContactPoint (0..*)
  birthDate: date (0..1)
  address : address (0..*)   
}

entity "Device - CIED" as cied {
  id : string <<generated>>
  --
  identifier: Identifier (0..*)
  udiCarrier: BackboneElement (0..1)
  manufacturer: String (0..1)
  serialNumber: String (0..1)
  modelNumber: String (0..1)
  type: CodeableConcept (0..1)
  gateway: CodeableReference(Monitor) (0..*)
}

entity "Device - Monitor" as monitor {
  id : string <<generated>>
  --
  identifier: Identifier (0..*)
  udiCarrier: BackboneElement (0..1)
  manufacturer: String (0..1)
  serialNumber: String (0..1)
  modelNumber: String (0..1)
  type: CodeableConcept (0..1)
}
/' - 3/19/25 remove encounter and device association from connectivity use case
entity "DeviceAssociation" as devassoc {
    id: id <<1..1>>
    --
    identifier: Identifier (0..*)
    device: Reference(Device) (1..1)
    status: CodeableConcept (1..1)
    subject: Reference(Patient) (0..1)   
}
'/

entity "Observation - Connectivity Status" as Connectivity {
    id : string <<generated>> (0..*)
    status : code (1..1)
    code : CodeableConcept (1..1)
    subject : Reference(Patient) (0..1)
    effective : dateTime (1..1)
    note : Annotation (0..*)
    device : Reference(CIED) (1..1)
    connectivityStatus : BackboneElement (1..0)
    connectivityModifier : BackboneElement (0..1)
    lastCiedConnectivityDate : BackboneElement (0..1)
    lastMonitorConnectivityDate : BackboneElement (0..1)
    nextCiedConnectivityDate : BackboneElement (0..1)
    nextMonitorConnectivityDate : BackboneElement (0..1)
    lastRemoteInterrogationDate : BackboneElement (0..1)
    nextRemoteInterrogationDate : BackboneElement (0..1)
    connectionInterval : BackboneElement (0..1)
}
/' - 3/19/25 remove encounter and device association from connectivity use case
entity "Encounter" as Encounter {
  *id : string <<generated>>
  --
  identifier : Identifier: (1..*)
  status : Code (1..1)
  type: CodeableConcept (1..*)
  subject: Reference(Patient) (1..1) 
  participant: Reference(Device) (1..*)
  actualPeriod: Period (0..1)
  plannedStartDate (0..1)
}
'/

Connectivity |o..|| Patient
Connectivity ||..|| cied
cied |o..|| monitor
/' - 3/19/25 remove encounter and device association from connectivity
devassoc ||..|| cied
devassoc ||..o| Patient
devassoc ||..o| monitor
Encounter ||..|| Patient
Encounter ||..|| cied
Encounter ||..|| monitor
'/
@enduml